// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEngines() {
  return window['go']['main']['App']['GetEngines']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVoices(arg1, arg2) {
  return window['go']['main']['App']['GetVoices'](arg1, arg2);
}

export function Play(arg1) {
  return window['go']['main']['App']['Play'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
