// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProfile(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateProfile'](arg1, arg2, arg3);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function EventSubscribe(arg1, arg2) {
  return window['go']['main']['App']['EventSubscribe'](arg1, arg2);
}

export function EventTrigger(arg1, arg2) {
  return window['go']['main']['App']['EventTrigger'](arg1, arg2);
}

export function GenerateServerCommand(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateServerCommand'](arg1, arg2, arg3, arg4);
}

export function GetAvailableModels() {
  return window['go']['main']['App']['GetAvailableModels']();
}

export function GetConfigSchema() {
  return window['go']['main']['App']['GetConfigSchema']();
}

export function GetEngines() {
  return window['go']['main']['App']['GetEngines']();
}

export function GetEnginesForProfile(arg1) {
  return window['go']['main']['App']['GetEnginesForProfile'](arg1);
}

export function GetModelVoices(arg1, arg2) {
  return window['go']['main']['App']['GetModelVoices'](arg1, arg2);
}

export function GetProfile(arg1) {
  return window['go']['main']['App']['GetProfile'](arg1);
}

export function GetProfileSettings(arg1) {
  return window['go']['main']['App']['GetProfileSettings'](arg1);
}

export function GetProfileSettingsSchema() {
  return window['go']['main']['App']['GetProfileSettingsSchema']();
}

export function GetProfileVoices(arg1) {
  return window['go']['main']['App']['GetProfileVoices'](arg1);
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetServerLogs() {
  return window['go']['main']['App']['GetServerLogs']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function IsPiperGPUAvailable() {
  return window['go']['main']['App']['IsPiperGPUAvailable']();
}

export function Play(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Play'](arg1, arg2, arg3, arg4);
}

export function ProcessScript(arg1, arg2) {
  return window['go']['main']['App']['ProcessScript'](arg1, arg2);
}

export function RefreshModels() {
  return window['go']['main']['App']['RefreshModels']();
}

export function ReloadVoicePacks() {
  return window['go']['main']['App']['ReloadVoicePacks']();
}

export function SaveProfileSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveProfileSettings'](arg1, arg2);
}

export function SaveProfileVoices(arg1, arg2) {
  return window['go']['main']['App']['SaveProfileVoices'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function StartDaemonServer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartDaemonServer'](arg1, arg2, arg3, arg4);
}

export function StopDaemonServer() {
  return window['go']['main']['App']['StopDaemonServer']();
}
