// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function CreateProfile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DeleteProfile(arg1:string):Promise<void>;

export function EventSubscribe(arg1:string,arg2:any):Promise<void>;

export function EventTrigger(arg1:string,arg2:any):Promise<void>;

export function GenerateServerCommand(arg1:string,arg2:number,arg3:string,arg4:string):Promise<string>;

export function GetAvailableModels():Promise<string>;

export function GetConfigSchema():Promise<string>;

export function GetEngines():Promise<string>;

export function GetEnginesForProfile(arg1:string):Promise<string>;

export function GetModelVoices(arg1:string,arg2:string):Promise<string>;

export function GetProfile(arg1:string):Promise<string>;

export function GetProfileSettings(arg1:string):Promise<string>;

export function GetProfileSettingsSchema():Promise<string>;

export function GetProfileVoices(arg1:string):Promise<string>;

export function GetProfiles():Promise<string>;

export function GetServerLogs():Promise<string>;

export function GetServerStatus():Promise<string>;

export function GetSetting(arg1:string):Promise<any>;

export function GetSettings():Promise<config.Base>;

export function GetStatus():Promise<string>;

export function Play(arg1:string,arg2:boolean,arg3:string,arg4:string):Promise<void>;

export function ProcessScript(arg1:string,arg2:string):Promise<void>;

export function RefreshModels():Promise<void>;

export function ReloadVoicePacks():Promise<void>;

export function SaveProfileSettings(arg1:string,arg2:string):Promise<void>;

export function SaveProfileVoices(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:config.Base):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:string):Promise<string>;

export function StartDaemonServer(arg1:string,arg2:number,arg3:string,arg4:string):Promise<string>;

export function StopDaemonServer():Promise<string>;
