// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSettings():Promise<string>;

export function Play(arg1:string):Promise<string>;

export function SaveSettings(arg1:string):Promise<void>;
